"""Create all tables

Revision ID: 09ed9da00e6f
Revises: 
Create Date: 2025-04-22 12:38:13.252074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ed9da00e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.create_table('riot_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riot_profiles_user_id'), 'riot_profiles', ['user_id'], unique=False)
    op.create_table('kda_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_profile_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('kda_ratio', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['riot_profile_id'], ['riot_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kda_logs_riot_profile_id'), 'kda_logs', ['riot_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kda_logs_riot_profile_id'), table_name='kda_logs')
    op.drop_table('kda_logs')
    op.drop_index(op.f('ix_riot_profiles_user_id'), table_name='riot_profiles')
    op.drop_table('riot_profiles')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
