"""Fix table args, remove user_id, add join table

Revision ID: 61c1d4f3d892
Revises: 09ed9da00e6f
Create Date: 2025-04-23 19:44:51.613606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c1d4f3d892'
down_revision: Union[str, None] = '09ed9da00e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_riot_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('riot_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['riot_profile_id'], ['riot_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'riot_profile_id')
    )
    op.alter_column('kda_logs', 'riot_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_kda_logs_riot_profile_id', table_name='kda_logs')
    op.create_index(op.f('ix_kda_logs_riot_profile_id'), 'kda_logs', ['riot_profile_id'], unique=True)
    op.add_column('riot_profiles', sa.Column('puuid', sa.String(), nullable=False))
    op.drop_index('ix_riot_profiles_user_id', table_name='riot_profiles')
    op.create_index(op.f('ix_riot_profiles_puuid'), 'riot_profiles', ['puuid'], unique=True)
    op.create_unique_constraint('riot_profiles_puuid', 'riot_profiles', ['puuid'])
    op.drop_constraint('riot_profiles_user_id_fkey', 'riot_profiles', type_='foreignkey')
    op.drop_column('riot_profiles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riot_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('riot_profiles_user_id_fkey', 'riot_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint('riot_profiles_puuid', 'riot_profiles', type_='unique')
    op.drop_index(op.f('ix_riot_profiles_puuid'), table_name='riot_profiles')
    op.create_index('ix_riot_profiles_user_id', 'riot_profiles', ['user_id'], unique=False)
    op.drop_column('riot_profiles', 'puuid')
    op.drop_index(op.f('ix_kda_logs_riot_profile_id'), table_name='kda_logs')
    op.create_index('ix_kda_logs_riot_profile_id', 'kda_logs', ['riot_profile_id'], unique=False)
    op.alter_column('kda_logs', 'riot_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user_riot_profiles')
    # ### end Alembic commands ###
